### ISSUE TITLE
getting error after running npm install

### ISSUE THREAD

**Issue by husseinsaleh22** [ebrahimMaher/dalilmobarmg#12]
ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app/src/polyfills-plugin.js:1
Error: /Users/husseinsaleh/Downloads/hs/dalilmobarmg/.nuxt/client.js: Cannot find module '@babel/preset-env/lib/utils'
Require stack:
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app/src/polyfills-plugin.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app/src/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/config/files/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/babel-loader/lib/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/loader-runner/lib/loadLoader.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/NormalModule.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/Compiler.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/webpack.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/nuxt.config.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/config/dist/config.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/cli/dist/cli-index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/cli/dist/cli.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/nuxt/bin/nuxt.js
    at PluginPass.Program (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app/src/polyfills-plugin.js:15:34)
    at newFn (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/visitors.js:159:21)
    at NodePath._call (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/path/context.js:84:31)
    at TraversalContext.visitQueue (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/index.js:50:34)
    at transformFile (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/transformation/index.js:83:29)
    at transformFile.next (<anonymous>)
    at run (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:261:32)
    at /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:223:11)
    at /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:189:28
    at /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/gensync-utils/async.js:72:7
    at /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:113:33
    at step (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:287:14)
    at /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:223:11)
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js app[1]

**Comment by husseinsaleh22** [comment]
script.js:1 Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app-edge/src/polyfills-plugin.js:1
Error: /Users/husseinsaleh/Downloads/hs/dalilmobarmg/.nuxt/color-mode/script.js: Cannot find module '@babel/preset-env/lib/utils'
Require stack:
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app-edge/src/polyfills-plugin.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app-edge/src/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/config/files/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/babel-loader/lib/index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/loader-runner/lib/loadLoader.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/NormalModule.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/Compiler.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/webpack/lib/webpack.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/nuxt.config.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/config-edge/dist/config.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/cli-edge/dist/cli-index.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/cli-edge/dist/cli.js
- /Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/nuxt-edge/bin/nuxt.js
    at PluginPass.Program (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@nuxt/babel-preset-app-edge/src/polyfills-plugin.js:15:34)
    at newFn (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/visitors.js:159:21)
    at NodePath._call (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/path/context.js:84:31)
    at TraversalContext.visitQueue (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/traverse/lib/index.js:50:34)
    at transformFile (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/transformation/index.js:83:29)
    at transformFile.next (<anonymous>)
    at run (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:261:32)
    at :3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:223:11)
    at :3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:189:28
    at :3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/@babel/core/lib/gensync-utils/async.js:72:7
    at :3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:113:33
    at step (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:287:14)
    at :3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (:3000/Users/husseinsaleh/Downloads/hs/dalilmobarmg/node_modules/gensync/index.js:223:11)
    at eval (script.js:1:7)
    at ./.nuxt/color-mode/script.js (default~app.js:58:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at 0 (default~app.js:2448:1)
    at __webpack_require__ (runtime.js:854:30)
    at checkDeferredModules (runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (runtime.js:33:19)
    at app.js:1:57
